### Pandas-DataFrame And Series

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

# Series -> 1D array object
# DataFrame -> 2D array object

In [33]:
print('Hello')

Hello

In [34]:
pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\desktop\python for ds\.venv\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\lenovo\desktop\python for ds\.venv\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\desktop\python for ds\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\desktop\python for ds\.venv\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\desktop\python for ds\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [35]:
import pandas as pd

### Series

In [36]:
## Series

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [37]:
## Create a Series From a Dictionary
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [38]:
data = [10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

### DataFrame

In [47]:
## DataFrame - 2D mutable,  hetrogenous tabular data structred with row and column

## create a dataframe from a dictionary of list

data = {
    'name':['Krish','John','Jack'],
    'age':[24,56,77],
    'city':['Patna','Bangalore','New York']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    name  age       city
0  Krish   24      Patna
1   John   56  Bangalore
2   Jack   77   New York
<class 'pandas.DataFrame'>

In [49]:
## Create a DataFrame from a List of Dictionary

data1=[
{'Name': 'Krish', 'Age': 32, 'City': 'Bangalore'}, 
{'Name': 'John', 'Age': 34, 'City': 'Bangalore'}, 
{'Name': 'Bappy', 'Age':32, 'City': 'Bangalore'},
{'Name': 'JAck', 'Age':32, 'City': 'Bangalore'}
]
df=pd.DataFrame(data1)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.DataFrame'>

In [41]:
df = pd.read_csv('sales_data.csv')
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [52]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [50]:
## Accessing Data From DataFrame
data

{'name': ['Krish', 'John', 'Jack'],
 'age': [24, 56, 77],
 'city': ['Patna', 'Bangalore', 'New York']}

In [53]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [54]:
df['Name']

0    Krish
1     John
2    Bappy
3     JAck
Name: Name, dtype: str

In [55]:
type(df['Name'])

pandas.Series

In [59]:
# To go to the row index
df.loc[0]

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [62]:
# To go to the col index
df.iloc[0]

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [66]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [65]:
## Accessing a specified element
df.at[1,'Age']

np.int64(34)

In [69]:
## Accessing a specified element using iat
df.iat[2,2]

'Bangalore'

### Data Manipulation with DataFrames

In [74]:
# Adding a new column
import pandas as pd
df['Salary'] = pd.Series([50000,60000,70000])
df

    Name  Age       City   Salary
0  Krish   32  Bangalore  50000.0
1   John   34  Bangalore  60000.0
2  Bappy   32  Bangalore  70000.0
3   JAck   32  Bangalore      NaN

In [ ]:
## Remove a column
df.drop('Salary',axis=1) #drop is not a permanent operation

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [77]:
df.drop('Salary', axis=1, inplace=True)

In [78]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [79]:
## Add age to the column
df['Age'] = df['Age'] + 1

In [80]:
df

    Name  Age       City
0  Krish   33  Bangalore
1   John   35  Bangalore
2  Bappy   33  Bangalore
3   JAck   33  Bangalore

In [81]:
# drop based on row
df

    Name  Age       City
0  Krish   33  Bangalore
1   John   35  Bangalore
2  Bappy   33  Bangalore
3   JAck   33  Bangalore

In [ ]:
df.drop(0) #dropped first row completely

    Name  Age       City
1   John   35  Bangalore
2  Bappy   33  Bangalore
3   JAck   33  Bangalore

In [83]:
df.drop(0, inplace=True)

In [84]:
df

    Name  Age       City
1   John   35  Bangalore
2  Bappy   33  Bangalore
3   JAck   33  Bangalore

In [93]:
# Display the data types of each column 

print("Data types: \n", df.dtypes)

# Describe the DataFrame 

print("Statistical summary:\n", df.describe())

Data types:
 Name      str
Age     int64
City      str
dtype: object
Statistical summary:
              Age
count   3.000000
mean   33.666667
std     1.154701
min    33.000000
25%    33.000000
50%    33.000000
75%    34.000000
max    35.000000

In [94]:
df.describe() #statistical summary

             Age
count   3.000000
mean   33.666667
std     1.154701
min    33.000000
25%    33.000000
50%    33.000000
75%    34.000000
max    35.000000