In [2]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [3]:
### Load the ANN trained model, sclaer pickle file, onehot
model = load_model('model.h5')

##load the encoder and scaler
with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_geo = pickle.load(file)

with  open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [4]:
# Example input data
input_data = {
'CreditScore': 600,
'Geography': 'France',
'Gender': 'Male',
'Age': 40,
'Tenure': 3,
'Balance': 60000,
'NumOfProducts': 2,
'HasCrCard': 1,
'IsActiveMember': 1,
'EstimatedSalary': 50000
}

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
onehot_encoder_geo = OneHotEncoder()

geo_encoded = onehot_encoder_geo.fit_transform(
    [[input_data['Geography']]]
).toarray()

In [17]:
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

   Geography_France
0               1.0

In [19]:
input_data = pd.DataFrame([input_data])

In [20]:
## Combine one-hot encoded columns with input data
input_data = pd.concat(
    [input_data.reset_index(drop=True), geo_encoded_df],
    axis=1
)

In [25]:
## Geography and Gender => Categorical Variables

# Gender -> 0 and 1
label_encoder_gender = LabelEncoder()
input_data['Gender'] = label_encoder_gender.fit_transform(input_data['Gender'])

In [26]:
input_data

   CreditScore Geography  ...  EstimatedSalary  Geography_France
0          600    France  ...            50000               1.0

[1 rows x 11 columns]

In [27]:
input_df = input_data
input_df

   CreditScore Geography  ...  EstimatedSalary  Geography_France
0          600    France  ...            50000               1.0

[1 rows x 11 columns]

In [31]:
print(input_df['Gender'])

0    <bound method LabelEncoder.transform of LabelE...
Name: Gender, dtype: object

In [32]:
input_df['Gender'] = 'Male'

In [33]:
input_df['Gender'] = 'Female'

In [35]:
from sklearn.preprocessing import LabelEncoder

label_encoder_gender = LabelEncoder()

label_encoder_gender.fit(['Male', 'Female'])

LabelEncoder()

In [36]:
input_df['Gender'] = label_encoder_gender.transform(
    input_df['Gender']
)

input_df

   CreditScore Geography  ...  EstimatedSalary  Geography_France
0          600    France  ...            50000               1.0

[1 rows x 11 columns]

In [37]:
print(label_encoder_gender.classes_)

['Female' 'Male']

In [39]:
print(input_df['Gender'])

0    0
Name: Gender, dtype: int64

In [40]:
input_df = input_df.drop(['Geography'], axis=1)

In [43]:
input_df

   CreditScore  Gender  Age  ...  IsActiveMember  EstimatedSalary  Geography_France
0          600       0   40  ...               1            50000               1.0

[1 rows x 10 columns]

In [44]:
input_df['Geography_France'] = 1
input_df['Geography_Germany'] = 0
input_df['Geography_Spain'] = 0

In [45]:
input_df['Geography_France'] = 0
input_df['Geography_Germany'] = 1
input_df['Geography_Spain'] = 0

In [46]:
input_df['Geography_France'] = 0
input_df['Geography_Germany'] = 0
input_df['Geography_Spain'] = 1

In [48]:
#input_df = input_df.drop(['Geography'], axis=1)

In [49]:
input_scaled = scaler.transform(input_df)

In [50]:
prediction = model.predict(input_scaled)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step
[[0.08111043]]

In [51]:
prediction_proba = prediction[0][0]

if prediction_proba > 0.5:
    print("Customer is likely to churn")
else:
    print("Customer is not likely to churn")

Customer is not likely to churn