### Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
<
3. Target Guided Ordinal Encoding


### Nominal/OHE Encoding


One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent one hot encoding as follows:


1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
# Create a Single DataFrame
df = pd.DataFrame({
    'color':['red', 'blue', 'green', 'red', 'blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [5]:
# Convert it into some additional features by using OHE

# Create an instance of OHE
encoder = OneHotEncoder()

In [7]:
# Perform fit and transform
encoded = encoder.fit_transform(df[['color']]).toarray()

In [8]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [10]:
import pandas as pd
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [13]:
# For new data
encoder.transform([['blue']]).toarray()

c:\Users\Lenovo\Desktop\Python For DS\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [14]:
pd.concat([df,encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

In [20]:
import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
# Convert sex smoker day and time into numerical data

In [37]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

In [38]:
# 1. Load Dataset
df2 = sns.load_dataset('tips')

In [39]:
#2. Select categorical column
categorical_cols = ['sex', 'smoker', 'day', 'time']

In [40]:
#3. Create encoder instance
encoder = OneHotEncoder()

In [41]:
#4. Fit and transform
encoded = encoder.fit_transform(df[categorical_cols]).toarray()

In [42]:
# 5. convert to Dataframe with proper column names
encoded_df  = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(categorical_cols))

In [43]:
#6. Concatenate with original dataframe 
final_df = pd.concat([df.drop(columns=categorical_cols), encoded_df], axis=1)

In [44]:
# 7. Transform new data
encoder.transform([['Male', 'Yes', 'Sun', 'Dinner']]).toarray()

c:\Users\Lenovo\Desktop\Python For DS\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 1., 0., 1., 0., 0., 1., 0., 1., 0.]])

In [45]:
#8. view result
final_df.head()

   total_bill   tip  size  ...  day_Thur  time_Dinner  time_Lunch
0       16.99  1.01     2  ...       0.0          1.0         0.0
1       10.34  1.66     3  ...       0.0          1.0         0.0
2       21.01  3.50     3  ...       0.0          1.0         0.0
3       23.68  3.31     2  ...       0.0          1.0         0.0
4       24.59  3.61     4  ...       0.0          1.0         0.0

[5 rows x 13 columns]

### Label Encoding

Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [48]:
# Create a Single DataFrame
df = pd.DataFrame({
    'color':['red', 'blue', 'green', 'red', 'blue']
})

In [49]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [50]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [51]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\Lenovo\Desktop\Python For DS\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

In [54]:
lbl_encoder.transform([['red']])

c:\Users\Lenovo\Desktop\Python For DS\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [55]:
lbl_encoder.transform([['blue']])

c:\Users\Lenovo\Desktop\Python For DS\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [56]:
lbl_encoder.transform([['green']])

c:\Users\Lenovo\Desktop\Python For DS\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

## Ordinal Encoding

It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:
1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-graduate: 4

In [57]:
## Ordinal Encoding

In [59]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

df = pd.DataFrame({
    'size':['small', 'medium', 'large', 'medium','small', 'large']
})

In [60]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [62]:
## Assogn rankings
# create an instanc eof ordinal encoder and perform fir_transform
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [63]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [66]:
# for new data
encoder.transform([['small']])

c:\Users\Lenovo\Desktop\Python For DS\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

### Target Guided Ordinal Encoding


It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.


In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [68]:
import pandas as pd
#create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['New York', "London", 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 300, 250, 180, 320]
})

In [69]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [73]:
# price -> target variable
# try to convert this categorical feature based on the target variable
# Based on mean and median

mean_price = df.groupby('city')['price'].mean().to_dict()

In [74]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [75]:
df['city_encoded'] = df['city'].map(mean_price)

In [76]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [78]:
df[['price', 'city_encoded']]

   price  city_encoded
0    200         190.0
1    150         150.0
2    300         310.0
3    250         250.0
4    180         190.0
5    320         310.0

In [81]:
import seaborn as sns

df2 = sns.load_dataset('tips')

In [82]:
# convert time based on the total bill
 # Initially based on price encode city

 # Now, based on total_bill encode time

In [84]:
mean_bill_price = df2.groupby('time')['total_bill'].mean().to_dict()

In [85]:
mean_bill_price

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [87]:
df2['time_encoded'] = df2['time'].map(mean_bill_price)

In [88]:
df2

     total_bill   tip     sex smoker   day    time  size time_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2    20.797159
1         10.34  1.66    Male     No   Sun  Dinner     3    20.797159
2         21.01  3.50    Male     No   Sun  Dinner     3    20.797159
3         23.68  3.31    Male     No   Sun  Dinner     2    20.797159
4         24.59  3.61  Female     No   Sun  Dinner     4    20.797159
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.797159
240       27.18  2.00  Female    Yes   Sat  Dinner     2    20.797159
241       22.67  2.00    Male    Yes   Sat  Dinner     2    20.797159
242       17.82  1.75    Male     No   Sat  Dinner     2    20.797159
243       18.78  3.00  Female     No  Thur  Dinner     2    20.797159

[244 rows x 8 columns]

In [90]:
df2[['total_bill', 'time_encoded']]

     total_bill time_encoded
0         16.99    20.797159
1         10.34    20.797159
2         21.01    20.797159
3         23.68    20.797159
4         24.59    20.797159
..          ...          ...
239       29.03    20.797159
240       27.18    20.797159
241       22.67    20.797159
242       17.82    20.797159
243       18.78    20.797159

[244 rows x 2 columns]